INSERT INTO `cuisine` (`id`, `name`) VALUES(1, 'amerikai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(2, 'angol');
INSERT INTO `cuisine` (`id`, `name`) VALUES(3, 'afrikai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(4, 'ausztrál');
INSERT INTO `cuisine` (`id`, `name`) VALUES(5, 'belga');
INSERT INTO `cuisine` (`id`, `name`) VALUES(6, 'bolgár');
INSERT INTO `cuisine` (`id`, `name`) VALUES(7, 'cseh');
INSERT INTO `cuisine` (`id`, `name`) VALUES(8, 'dél-amerikai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(9, 'erdélyi');
INSERT INTO `cuisine` (`id`, `name`) VALUES(10, 'francia');
INSERT INTO `cuisine` (`id`, `name`) VALUES(11, 'fúziós');
INSERT INTO `cuisine` (`id`, `name`) VALUES(12, 'görög');
INSERT INTO `cuisine` (`id`, `name`) VALUES(13, 'holland');
INSERT INTO `cuisine` (`id`, `name`) VALUES(14, 'horvát');
INSERT INTO `cuisine` (`id`, `name`) VALUES(15, 'indiai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(16, 'japán');
INSERT INTO `cuisine` (`id`, `name`) VALUES(17, 'kínai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(18, 'lengyel');
INSERT INTO `cuisine` (`id`, `name`) VALUES(19, 'magyar');
INSERT INTO `cuisine` (`id`, `name`) VALUES(20, 'máltai');
INSERT INTO `cuisine` (`id`, `name`) VALUES(21, 'mexikói');
INSERT INTO `cuisine` (`id`, `name`) VALUES(22, 'német');
INSERT INTO `cuisine` (`id`, `name`) VALUES(23, 'olasz');
INSERT INTO `cuisine` (`id`, `name`) VALUES(24, 'orosz');
INSERT INTO `cuisine` (`id`, `name`) VALUES(25, 'osztrák');
INSERT INTO `cuisine` (`id`, `name`) VALUES(26, 'pakisztáni');
INSERT INTO `cuisine` (`id`, `name`) VALUES(27, 'portugál');
INSERT INTO `cuisine` (`id`, `name`) VALUES(28, 'skandináv');
INSERT INTO `cuisine` (`id`, `name`) VALUES(29, 'skót');
INSERT INTO `cuisine` (`id`, `name`) VALUES(30, 'spanyol');
INSERT INTO `cuisine` (`id`, `name`) VALUES(31, 'svájci');
INSERT INTO `cuisine` (`id`, `name`) VALUES(32, 'szerb');
INSERT INTO `cuisine` (`id`, `name`) VALUES(33, 'szlovák');
INSERT INTO `cuisine` (`id`, `name`) VALUES(34, 'szlovén');
INSERT INTO `cuisine` (`id`, `name`) VALUES(35, 'távol-keleti');
INSERT INTO `cuisine` (`id`, `name`) VALUES(36, 'török');
INSERT INTO `cuisine` (`id`, `name`) VALUES(37, 'zsidó');
INSERT INTO `cuisine` (`id`, `name`) VALUES(38, 'arab');

INSERT INTO `ingredient` (`id`, `name`) VALUES(27, 'Áfonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(29, 'Áfonyadzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(34, 'Áfonyalevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(21, 'Afrikai harcsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(6, 'Ajvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(16, 'Akácméz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(24, 'Akácvirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES(7, 'Alaplé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1, 'Alma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(9, 'Almaecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(25, 'Almakompót');
INSERT INTO `ingredient` (`id`, `name`) VALUES(13, 'Almalé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(19, 'Almapaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(20, 'Almapüré');
INSERT INTO `ingredient` (`id`, `name`) VALUES(15, 'Aludttej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(8, 'Amarettó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(2, 'Ananász');
INSERT INTO `ingredient` (`id`, `name`) VALUES (14, 'Ananászkonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(18, 'Ananászlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES (22, 'Angolszalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES (12, 'Apró uborka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(23, 'Arab hétfűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(32, 'Árpaliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (31, 'Árpapehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES (5, 'Articsóka');
INSERT INTO `ingredient` (`id`, `name`) VALUES (33, 'Árvácska');
INSERT INTO `ingredient` (`id`, `name`) VALUES (30, 'Ásványvíz');
INSERT INTO `ingredient` (`id`, `name`) VALUES  (26, 'Aszalt áfonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES  (4, 'Aszalt gyümölcsök');
INSERT INTO `ingredient` (`id`, `name`) VALUES (11, 'Aszalt sárgabarack');
INSERT INTO `ingredient` (`id`, `name`) VALUES (10, 'Aszalt szilva');
INSERT INTO `ingredient` (`id`, `name`) VALUES (17, 'Aszkorbinsav');
INSERT INTO `ingredient` (`id`, `name`) VALUES (3, 'Avokádó');
INSERT INTO `ingredient` (`id`, `name`) VALUES (28, 'Ázsiai tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES (57, 'Babapiskóta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(44, 'Babérlevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(87, 'babpüré');
INSERT INTO `ingredient` (`id`, `name`) VALUES(41, 'Bacon');
INSERT INTO `ingredient` (`id`, `name`) VALUES(91, 'Bagel');
INSERT INTO `ingredient` (`id`, `name`) VALUES(68, 'Bagett');
INSERT INTO `ingredient` (`id`, `name`) VALUES (88, 'Baileys');
INSERT INTO `ingredient` (`id`, `name`) VALUES (42, 'Balzsamecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES (49, 'Bambuszrügy');
INSERT INTO `ingredient` (`id`, `name`) VALUES (38, 'Banán');
INSERT INTO `ingredient` (`id`, `name`) VALUES (60, 'Barackbefőtt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (70, 'Barackkonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES (75, 'Bárányborda');
INSERT INTO `ingredient` (`id`, `name`) VALUES (93, 'Báránycsülök');
INSERT INTO `ingredient` (`id`, `name`) VALUES (62, 'Báránygerinc');
INSERT INTO `ingredient` (`id`, `name`) VALUES (40, 'Bárányhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES (76, 'Báránykaraj');
INSERT INTO `ingredient` (`id`, `name`) VALUES (77, 'Barbecue szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES (53, 'Barna cukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES (85, 'Barna mártás');
INSERT INTO `ingredient` (`id`, `name`) VALUES (78, 'Barna rum');
INSERT INTO `ingredient` (`id`, `name`) VALUES (59, 'Barna sör');
INSERT INTO `ingredient` (`id`, `name`) VALUES (71, 'Barnarizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES (94, 'Barnarizsliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (35, 'Bazsalikom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(69, 'Bébikukorica');
INSERT INTO `ingredient` (`id`, `name`) VALUES (66, 'Bébirépa');
INSERT INTO `ingredient` (`id`, `name`) VALUES (96, 'Bébispenót');
INSERT INTO `ingredient` (`id`, `name`) VALUES  (61, 'Befőzőcukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES (92, 'Bejgli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(50, 'Birs');
INSERT INTO `ingredient` (`id`, `name`) VALUES (83, 'Birsalmasajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(82, 'Bodzabogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES (45, 'Bodzavirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES (73, 'Bolognai alap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(79, 'Bolognai szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(86, 'Borjúbríz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(63, 'Borjúcomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(39, 'Borjúhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(65, 'Borjúkaraj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(64, 'Borjúlábszár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(84, 'Borjúmáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(58, 'Borkén');
INSERT INTO `ingredient` (`id`, `name`) VALUES(47, 'Borkősav');
INSERT INTO `ingredient` (`id`, `name`) VALUES(37, 'Bors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(46, 'Borsikafű');
INSERT INTO `ingredient` (`id`, `name`) VALUES(95, 'Borslevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(67, 'Borsmentalevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(80, 'Brandy');
INSERT INTO `ingredient` (`id`, `name`) VALUES (54, 'Brazil dió - Paradió');
INSERT INTO `ingredient` (`id`, `name`) VALUES(89, 'Brie sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(43, 'Brokkoli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(55, 'Bulgur');
INSERT INTO `ingredient` (`id`, `name`) VALUES(36, 'Burgonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(97, 'Burgonyachips');
INSERT INTO `ingredient` (`id`, `name`) VALUES(81, 'Burgonyakeményítő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(51, 'Burgonyapehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(72, 'Burgonyapüré');
INSERT INTO `ingredient` (`id`, `name`) VALUES(52, 'Busa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(74, 'Búzacsíra');
INSERT INTO `ingredient` (`id`, `name`) VALUES(48, 'Búzadara');
INSERT INTO `ingredient` (`id`, `name`) VALUES(90, 'Búzafű');
INSERT INTO `ingredient` (`id`, `name`) VALUES(56, 'Búzakorpa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(114, 'Camembert sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(111, 'Cannelloni');
INSERT INTO `ingredient` (`id`, `name`) VALUES(136, 'Carbonara alap');
INSERT INTO `ingredient` (`id`, `name`) VALUES (108, 'Cayenne bors');
INSERT INTO `ingredient` (`id`, `name`) VALUES (102, 'Cékla');
INSERT INTO `ingredient` (`id`, `name`) VALUES(130, 'Céklalé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(119, 'Cérnametélt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(121, 'Cheddar sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(131, 'Chiamag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(106, 'Chili');
INSERT INTO `ingredient` (`id`, `name`) VALUES(125, 'Chiliolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(126, 'Chilipaszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(122, 'Chilipehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(134, 'Chilis kukorica konzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(118, 'Chiliszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES (110, 'Chorizo');
INSERT INTO `ingredient` (`id`, `name`) VALUES(132, 'Cider');
INSERT INTO `ingredient` (`id`, `name`) VALUES(135, 'Cigánymeggy');
INSERT INTO `ingredient` (`id`, `name`) VALUES(98, 'Citrom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(124, 'Citrom aroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(112, 'Citrombors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(103, 'Citromfű');
INSERT INTO `ingredient` (`id`, `name`) VALUES(117, 'Citromhéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(115, 'Citromlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES (120, 'Citromlekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(129, 'Citromsav');
INSERT INTO `ingredient` (`id`, `name`) VALUES(107, 'Cointreau');
INSERT INTO `ingredient` (`id`, `name`) VALUES(123, 'Cottage cheese');
INSERT INTO `ingredient` (`id`, `name`) VALUES(101, 'Crème fraîche');
INSERT INTO `ingredient` (`id`, `name`) VALUES(140, 'Csalán');
INSERT INTO `ingredient` (`id`, `name`) VALUES(175, 'Császárszalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(142, 'Csemegekukorica');
INSERT INTO `ingredient` (`id`, `name`) VALUES (147, 'Csemegeuborka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(141, 'Cseresznye');
INSERT INTO `ingredient` (`id`, `name`) VALUES (166, 'Cseresznyebefőtt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (167, 'Cseresznyepaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES (139, 'Csicseriborsó');
INSERT INTO `ingredient` (`id`, `name`) VALUES  (178, 'Csicseriborsó (konzerv)');
INSERT INTO `ingredient` (`id`, `name`) VALUES  (165, 'Csigatészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES (146, 'Csiperkegomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(145, 'Csipkebogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(164, 'Csipkebogyó lekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(148, 'Csípős fűszerpaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES (150, 'Csípős kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(144, 'Csírák');
INSERT INTO `ingredient` (`id`, `name`) VALUES(138, 'Csirke');
INSERT INTO `ingredient` (`id`, `name`) VALUES(149, 'Csirke alaplé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(154, 'Csirke alsócomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES (156, 'Csirke felsőcomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES (214, 'Csirke fűszersó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(176, 'Csirkeaprólék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(179, 'Csirkebőr');
INSERT INTO `ingredient` (`id`, `name`) VALUES(152, 'Csirkecomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(160, 'Csirkefarhát');
INSERT INTO `ingredient` (`id`, `name`) VALUES(174, 'Csirkeláb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(143, 'Csirkemáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(151, 'Csirkemell (csontos)');
INSERT INTO `ingredient` (`id`, `name`) VALUES(171, 'Csirkemell filé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(155, 'Csirkemell sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(157, 'Csirkenyak');
INSERT INTO `ingredient` (`id`, `name`) VALUES(153, 'Csirkeszárny');
INSERT INTO `ingredient` (`id`, `name`) VALUES(158, 'Csirkeszív');
INSERT INTO `ingredient` (`id`, `name`) VALUES(162, 'Csirkezúza');
INSERT INTO `ingredient` (`id`, `name`) VALUES (169, 'Csokiszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(137, 'Csokoládé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(173, 'Csokoládé fagylalt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (177, 'Csokoládés gabonagolyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(168, 'Csokoládés puding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(159, 'Csokoládés pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(170, 'Csontlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(161, 'Csontos sertéskaraj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(172, 'Csöves kukorica');
INSERT INTO `ingredient` (`id`, `name`) VALUES (163, 'Csuszatészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(99, 'Cukkini');
INSERT INTO `ingredient` (`id`, `name`) VALUES (100, 'Cukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(105, 'Cukorborsó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(128, 'Cukormentes csokoládé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(133, 'Cukorszirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(116, 'Cukrozatlan kakaópor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(127, 'Curacao szirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(109, 'Curry levél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(113, 'Curry paszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(104, 'Curry por');
INSERT INTO `ingredient` (`id`, `name`) VALUES(182, 'Darált marhahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(183, 'Darált pulykahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(185, 'Darált sertéshús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(181, 'Datolya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(188, 'Debreceni kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES (189, 'Diákcsemege');
INSERT INTO `ingredient` (`id`, `name`) VALUES(184, 'Dijoni mustár');
INSERT INTO `ingredient` (`id`, `name`) VALUES (180, 'Dió');
INSERT INTO `ingredient` (`id`, `name`) VALUES (187, 'Dióolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(191, 'Disznósajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(186, 'Disznózsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES (190, 'Durumliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (193, 'Ecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES (213, 'Ecetes almapaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(200, 'Ecetes cékla');
INSERT INTO `ingredient` (`id`, `name`) VALUES(199, 'Ecetes gyöngyhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(204, 'Ecetes torma');
INSERT INTO `ingredient` (`id`, `name`) VALUES (197, 'Edami sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(224, 'Édes fehérbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(226, 'Édes rosé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(225, 'Édes vörösbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(228, 'Édes-savanyú mártás');
INSERT INTO `ingredient` (`id`, `name`) VALUES(215, 'Édesburgonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES (230, 'Édesgyökér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(223, 'Édesítőszer');
INSERT INTO `ingredient` (`id`, `name`) VALUES(216, 'Édeskömény');
INSERT INTO `ingredient` (`id`, `name`) VALUES(217, 'Édesköménymag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(194, 'Egres');
INSERT INTO `ingredient` (`id`, `name`) VALUES(218, 'Élesztő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(229, 'Élesztőpehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(198, 'Ementáli sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(192, 'Eper');
INSERT INTO `ingredient` (`id`, `name`) VALUES(205, 'Eperdzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(206, 'Eperkonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(208, 'Eperlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(209, 'Eperlekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(202, 'Eperlevél tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES (210, 'Eperszörp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(211, 'Epres puding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(196, 'Epres pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(195, 'Erdei gyümölcs mix');
INSERT INTO `ingredient` (`id`, `name`) VALUES(201, 'Erdei gyümölcslekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(203, 'Erdélyi szalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(212, 'Erythritol');
INSERT INTO `ingredient` (`id`, `name`) VALUES(227, 'Étcsokoládé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(221, 'Ételfesték');
INSERT INTO `ingredient` (`id`, `name`) VALUES(220, 'Ételízesítő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(222, 'Éticsiga');
INSERT INTO `ingredient` (`id`, `name`) VALUES(219, 'Étkezési keményítő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(207, 'Ezersziget öntet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(281, 'Fafülgomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES (236, 'Fahéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES (256, 'Fahéjrúd');
INSERT INTO `ingredient` (`id`, `name`) VALUES(251, 'Fehér bors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(250, 'Fehér csokoládé');
INSERT INTO `ingredient` (`id`, `name`) VALUES (265, 'Fehér mustármag');
INSERT INTO `ingredient` (`id`, `name`) VALUES (271, 'Fehér rum');
INSERT INTO `ingredient` (`id`, `name`) VALUES(241, 'Fehér spárga');
INSERT INTO `ingredient` (`id`, `name`) VALUES(253, 'Fehérbab');
INSERT INTO `ingredient` (`id`, `name`) VALUES (249, 'Fehérbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(239, 'Fehérborecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(259, 'Fehérpecsenye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(235, 'Fehérrépa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(233, 'Fejessaláta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(242, 'Fejtett bab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(272, 'Fekete áfonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(257, 'Fekete bors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(254, 'Fekete olajbogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(245, 'Fekete retek');
INSERT INTO `ingredient` (`id`, `name`) VALUES(267, 'Fekete tea');
INSERT INTO `ingredient` (`id`, `name`) VALUES(262, 'Feketeerdő sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(244, 'Feketegyökér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(252, 'Feketekávé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(246, 'Feketekömény');
INSERT INTO `ingredient` (`id`, `name`) VALUES(247, 'Feketeribizli');
INSERT INTO `ingredient` (`id`, `name`) VALUES (268, 'Félédes rosé');
INSERT INTO `ingredient` (`id`, `name`) VALUES (266, 'Félédes vörösbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(273, 'Félszáraz fehérbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(270, 'Félszáraz rosé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(269, 'Félszáraz vörösbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(237, 'Fenyőmag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(240, 'Feta sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(234, 'Finomliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(280, 'Fogas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(231, 'Fokhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES (261, 'Fokhagymakrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(275, 'Fokhagymapor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(232, 'Földimogyoró');
INSERT INTO `ingredient` (`id`, `name`) VALUES(282, 'Főtt sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(258, 'Főtt tojás');
INSERT INTO `ingredient` (`id`, `name`) VALUES(276, 'Főzőhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(260, 'Főzőkolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(255, 'Főzőtejszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(277, 'Franciasaláta alap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(274, 'Frankfurti virsli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(263, 'Fusilli tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(243, 'Füge');
INSERT INTO `ingredient` (`id`, `name`) VALUES(278, 'Fügelekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(284, 'Füstölt lapocka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(287, 'Füstölt lazac');
INSERT INTO `ingredient` (`id`, `name`) VALUES(286, 'Füstölt oldalas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(264, 'Füstölt sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(248, 'Füstölt szalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(285, 'Füstölt tarja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(283, 'füstölt-főtt tarja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(238, 'Fűszerpaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(279, 'Fűszervaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(292, 'Garnéla');
INSERT INTO `ingredient` (`id`, `name`) VALUES(291, 'Gesztenye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(298, 'Gesztenyemassza');
INSERT INTO `ingredient` (`id`, `name`) VALUES(301, 'Gin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(303, 'Goji bogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(288, 'Gomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(302, 'Gombakonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(294, 'Gomolya sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(299, 'Gorgonzola');
INSERT INTO `ingredient` (`id`, `name`) VALUES(297, 'Görög joghurt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (293, 'Görögdinnye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(295, 'Graham-liszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(296, 'Grana Padano');
INSERT INTO `ingredient` (`id`, `name`) VALUES (290, 'Gránátalma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(289, 'Grépfrút');
INSERT INTO `ingredient` (`id`, `name`) VALUES(300, 'Gumicukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(309, 'Gyors rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(304, 'Gyömbér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(308, 'Gyömbérpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(313, 'Gyöngybab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(307, 'Gyöngyhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(306, 'Gyros fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(311, 'Gyufatészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(310, 'Gyulai kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(305, 'Gyümölcscukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(314, 'Gyümölcsjoghurt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(312, 'Gyümölcslé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(320, 'Habtejszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(315, 'Hajdina');
INSERT INTO `ingredient` (`id`, `name`) VALUES(319, 'Hajdinaliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(318, 'Hal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(329, 'Hal fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(328, 'Halolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(333, 'Halrudacska');
INSERT INTO `ingredient` (`id`, `name`) VALUES(321, 'Hamburger zsemle');
INSERT INTO `ingredient` (`id`, `name`) VALUES (330, 'Hamburgerhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(331, 'Hasábburgonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(317, 'Háztartási keksz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(316, 'Heck');
INSERT INTO `ingredient` (`id`, `name`) VALUES(325, 'Hegyes erős paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(326, 'Hering');
INSERT INTO `ingredient` (`id`, `name`) VALUES(324, 'Himalája só');
INSERT INTO `ingredient` (`id`, `name`) VALUES(327, 'Homár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(323, 'Hosszúmetélt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(322, 'Hot-dog kifli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(332, 'Hummusz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(335, 'Jalapeño');
INSERT INTO `ingredient` (`id`, `name`) VALUES(340, 'Jázmin rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(342, 'Jégcsapretek');
INSERT INTO `ingredient` (`id`, `name`) VALUES(341, 'Jégkocka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(339, 'Jégsaláta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(334, 'Joghurt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(336, 'Juharszirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(343, 'Juhhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(338, 'Juhsajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(337, 'Juhtúró');
INSERT INTO `ingredient` (`id`, `name`) VALUES(423, 'Kacsacomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(355, 'Kacsahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(356, 'Kacsamáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(394, 'Kacsamell');
INSERT INTO `ingredient` (`id`, `name`) VALUES(391, 'Kacsazsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(364, 'Kagyló');
INSERT INTO `ingredient` (`id`, `name`) VALUES(424, 'Kagylóhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(425, 'Kagylótészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(345, 'Kakaó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(454, 'Kakaóbab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(427, 'Kakas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(346, 'Kakukkfű');
INSERT INTO `ingredient` (`id`, `name`) VALUES(445, 'Kalács');
INSERT INTO `ingredient` (`id`, `name`) VALUES(426, 'Kamillavirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES(411, 'Kandírozott ananász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(402, 'Kandírozott citromhéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(403, 'Kandírozott narancshéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(397, 'Kápia paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(349, 'Kapor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(369, 'Káposzta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(439, 'Káposztalevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(354, 'Kapribogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(367, 'Karalábé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(449, 'Karalábélevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(430, 'Karamell öntet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(429, 'Karamellás puding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(405, 'Karamellás pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(380, 'Kárász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(371, 'Kardamom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(350, 'Karfiol');
INSERT INTO `ingredient` (`id`, `name`) VALUES(407, 'Kaukázusi kefir');
INSERT INTO `ingredient` (`id`, `name`) VALUES(347, 'Kávé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(441, 'Kávétejszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(360, 'Kaviár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(389, 'Kecskehús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(352, 'Kecskesajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(368, 'Kefir');
INSERT INTO `ingredient` (`id`, `name`) VALUES(455, 'Kefirgomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(386, 'Kéksajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(384, 'Keksz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(399, 'Kekszmorzsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(398, 'Kékszőlő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(377, 'Kelbimbó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(370, 'Kelkáposzta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(432, 'Kelkáposzta levél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(459, 'Kelt tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(415, 'Kendermag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(453, 'Kenguruhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(412, 'Kenőmájas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(433, 'Kentucky fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(383, 'Kenyér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(406, 'Kenyérszalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(348, 'Kesudió');
INSERT INTO `ingredient` (`id`, `name`) VALUES (438, 'Keszeg');
INSERT INTO `ingredient` (`id`, `name`) VALUES(381, 'Ketchup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(382, 'Kétszersült');
INSERT INTO `ingredient` (`id`, `name`) VALUES(376, 'Kifli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(392, 'Kígyóuborka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(361, 'Kínai kel');
INSERT INTO `ingredient` (`id`, `name`) VALUES(379, 'Kínai ötfűszer-keverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(431, 'Kínai tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(450, 'Kínai zöldségkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(428, 'Királyrák');
INSERT INTO `ingredient` (`id`, `name`) VALUES(358, 'Kivi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(408, 'Kockacukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(444, 'Kockasajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(422, 'Koffeinmentes kávé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(419, 'Koktélcseresznye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(446, 'Koktélparadicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(351, 'Koktélrák');
INSERT INTO `ingredient` (`id`, `name`) VALUES(365, 'Kókusz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(440, 'Kókuszchips');
INSERT INTO `ingredient` (`id`, `name`) VALUES(451, 'Kókuszcukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(442, 'Kókuszkrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(443, 'Kókuszliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(375, 'Kókuszolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(413, 'Kókuszos puding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(414, 'Kókuszos pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(395, 'Kókuszreszelék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(387, 'Kókusztej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(418, 'Kókusztejpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(390, 'Kókuszzsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(448, 'Kóla');
INSERT INTO `ingredient` (`id`, `name`) VALUES(374, 'Kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(435, 'Kolozsvári szalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(458, 'Komló');
INSERT INTO `ingredient` (`id`, `name`) VALUES(357, 'Konyak');
INSERT INTO `ingredient` (`id`, `name`) VALUES(457, 'Konyakmeggy');
INSERT INTO `ingredient` (`id`, `name`) VALUES(393, 'Konzerv paradicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(452, 'Konzerv vagdalthús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(359, 'Koriander');
INSERT INTO `ingredient` (`id`, `name`) VALUES(409, 'Kovász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(401, 'Kovászos uborka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(404, 'Kovászosuborka-lé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(434, 'Kökény');
INSERT INTO `ingredient` (`id`, `name`) VALUES(417, 'Kökénylekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(363, 'Köles');
INSERT INTO `ingredient` (`id`, `name`) VALUES(456, 'Kölesliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(362, 'Köménymag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(420, 'Körömvirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES(421, 'Körözött');
INSERT INTO `ingredient` (`id`, `name`) VALUES(344, 'Körte');
INSERT INTO `ingredient` (`id`, `name`) VALUES(447, 'Körtelé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(436, 'Kötözött sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(353, 'Közönséges tök');
INSERT INTO `ingredient` (`id`, `name`) VALUES(388, 'Krémsajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(410, 'Krémtúró');
INSERT INTO `ingredient` (`id`, `name`) VALUES(378, 'Krinolin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(400, 'Kruton');
INSERT INTO `ingredient` (`id`, `name`) VALUES(373, 'Kukoricadara');
INSERT INTO `ingredient` (`id`, `name`) VALUES(396, 'Kukoricakeményítő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(372, 'Kukoricaliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(416, 'Kukoricaolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(385, 'Kukoricapehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(437, 'Kukoricaszirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(366, 'Kurkuma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(495, 'Laktózmentes sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(496, 'Laktózmentes tej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(479, 'Lapkasajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(473, 'Lapzselatin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(472, 'Lasagne tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(466, 'Laskagomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(461, 'Lazac');
INSERT INTO `ingredient` (`id`, `name`) VALUES(478, 'Lecsókolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(492, 'Lecsópaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(469, 'Lekvár/ dzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(462, 'Lencse');
INSERT INTO `ingredient` (`id`, `name`) VALUES(465, 'Lenmag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(480, 'Lenmagliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(488, 'Lenmagolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(468, 'Lestyán');
INSERT INTO `ingredient` (`id`, `name`) VALUES(482, 'Levendula');
INSERT INTO `ingredient` (`id`, `name`) VALUES(485, 'Levendulaszirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(467, 'Levendulavirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES(484, 'Levescsont');
INSERT INTO `ingredient` (`id`, `name`) VALUES(483, 'Levesgyöngy');
INSERT INTO `ingredient` (`id`, `name`) VALUES(481, 'Libacomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(477, 'Libaháj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(463, 'Libahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES (471, 'Libamáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES (487, 'Libamájpástétom');
INSERT INTO `ingredient` (`id`, `name`) VALUES (476, 'Libamell');
INSERT INTO `ingredient` (`id`, `name`) VALUES (474, 'Libatepertő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(475, 'Libazsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(493, 'Licsi');
INSERT INTO `ingredient` (`id`, `name`) VALUES (494, 'Licsi konzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES (464, 'Lilahagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(460, 'Lime');
INSERT INTO `ingredient` (`id`, `name`) VALUES(489, 'Lime héja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(490, 'Lime levél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(491, 'Limelé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(470, 'Limoncello');
INSERT INTO `ingredient` (`id`, `name`) VALUES(486, 'Löncshús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(521, 'Madársaláta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(570, 'Madras curry');
INSERT INTO `ingredient` (`id`, `name`) VALUES(569, 'Magyaros fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(576, 'Májas hurka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(550, 'Májgombóc');
INSERT INTO `ingredient` (`id`, `name`) VALUES(551, 'Májkrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(513, 'Majonéz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(539, 'Majonézes torma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(514, 'Majoranna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(502, 'Mák');
INSERT INTO `ingredient` (`id`, `name`) VALUES (510, 'Makadámdió');
INSERT INTO `ingredient` (`id`, `name`) VALUES(526, 'Makaróni');
INSERT INTO `ingredient` (`id`, `name`) VALUES(581, 'Mákliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(506, 'Makréla');
INSERT INTO `ingredient` (`id`, `name`) VALUES(509, 'Málna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(546, 'Málnadzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(545, 'Málnalekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(552, 'Málnaszörp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(525, 'Mandarin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(500, 'Mandula');
INSERT INTO `ingredient` (`id`, `name`) VALUES(537, 'Mandulaaroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(538, 'Mandulapehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(547, 'Mandulatej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(582, 'Mandulavaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(522, 'Mangalica hús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(534, 'Mangalica szalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(536, 'Mangalica zsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(553, 'Mangalicatarja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(499, 'Mangó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(554, 'Maracuja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(518, 'Marcipán');
INSERT INTO `ingredient` (`id`, `name`) VALUES(512, 'Margarin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(555, 'Marha alaplé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(556, 'Marha hátszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(535, 'Marha velőscsont');
INSERT INTO `ingredient` (`id`, `name`) VALUES(528, 'Marhabélszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(531, 'Marhacomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(532, 'Marhacsont');
INSERT INTO `ingredient` (`id`, `name`) VALUES(533, 'Marhafartő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(501, 'Marhahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(530, 'Marhalábszár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(529, 'Marhalapocka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(561, 'Marhamáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(579, 'Marhanyak');
INSERT INTO `ingredient` (`id`, `name`) VALUES(578, 'Marhanyelv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(527, 'Marharostélyos');
INSERT INTO `ingredient` (`id`, `name`) VALUES(572, 'Marhavelő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(548, 'Marinált feta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(549, 'Marinált paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(540, 'Marinara szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(557, 'Martini Bianco');
INSERT INTO `ingredient` (`id`, `name`) VALUES(558, 'Martini Rosso');
INSERT INTO `ingredient` (`id`, `name`) VALUES(504, 'Mascarpone');
INSERT INTO `ingredient` (`id`, `name`) VALUES(515, 'Mazsola');
INSERT INTO `ingredient` (`id`, `name`) VALUES(511, 'Medvehagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(541, 'Medvehagyma pesto');
INSERT INTO `ingredient` (`id`, `name`) VALUES(508, 'Meggy');
INSERT INTO `ingredient` (`id`, `name`) VALUES(559, 'Meggybefőtt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(574, 'Meggydzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(571, 'Meggyfa levél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(562, 'Meggylé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(573, 'Meggylekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(580, 'Melasz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(563, 'Melegszendvicskrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(497, 'Menta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(560, 'Mentaszirup');
INSERT INTO `ingredient` (`id`, `name`) VALUES(577, 'Metélőhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(564, 'Mexikói alap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(544, 'Mexikói keverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(498, 'Méz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(575, 'Mezei cickafark');
INSERT INTO `ingredient` (`id`, `name`) VALUES(565, 'Mézes puszedli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(523, 'Mézeskalács fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(566, 'Mézkaramell');
INSERT INTO `ingredient` (`id`, `name`) VALUES(542, 'Milánói szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(507, 'Mirin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(543, 'Mogyoróolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(567, 'Mogyorós puding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(520, 'Mogyoróvaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(516, 'Mortadella');
INSERT INTO `ingredient` (`id`, `name`) VALUES(503, 'Mozzarella');
INSERT INTO `ingredient` (`id`, `name`) VALUES(517, 'Must');
INSERT INTO `ingredient` (`id`, `name`) VALUES(505, 'Mustár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(519, 'Mustármag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(524, 'Müzli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(568, 'Müzli mix');
INSERT INTO `ingredient` (`id`, `name`) VALUES(585, 'Nádcukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(593, 'Nápolyi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(586, 'Napraforgó olaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(584, 'Napraforgómag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(583, 'Narancs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(591, 'Narancs eszencia');
INSERT INTO `ingredient` (`id`, `name`) VALUES (597, 'Narancsaroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(592, 'Narancsdzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(598, 'Narancshéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(594, 'Narancslé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(589, 'Narancslekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(595, 'Narancsszörp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(599, 'Narancsvirág aroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(590, 'Naspolya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(600, 'Négyszínű bors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(587, 'Nektarin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(596, 'Nugátmassza');
INSERT INTO `ingredient` (`id`, `name`) VALUES(588, 'Nutella');
INSERT INTO `ingredient` (`id`, `name`) VALUES(601, 'Nyelvhal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(605, 'Nyírfacukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(603, 'Nyúlcomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(602, 'Nyúlhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(604, 'Nyúlmáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(606, 'Olajbogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(613, 'Olasz fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(607, 'Olívaolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(614, 'Orda');
INSERT INTO `ingredient` (`id`, `name`) VALUES(612, 'Orecchiette tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(608, 'Oregánó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(615, 'Oreo keksz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(609, 'Ostya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(611, 'Ostyalap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(610, 'Osztriga');
INSERT INTO `ingredient` (`id`, `name`) VALUES(616, 'Ördöghal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(622, 'Őrölt fűszerkömény');
INSERT INTO `ingredient` (`id`, `name`) VALUES(621, 'Őrölt kávé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(617, 'Őszibarack');
INSERT INTO `ingredient` (`id`, `name`) VALUES(623, 'Őszibarack konzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(620, 'Őszibarackdzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(619, 'Őszibaracklekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(625, 'Őzcomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(624, 'Őzgerinc');
INSERT INTO `ingredient` (`id`, `name`) VALUES(618, 'Őzhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(644, 'Pacal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(631, 'Padlizsán');
INSERT INTO `ingredient` (`id`, `name`) VALUES(697, 'Padlizsánkrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(668, 'Pálinka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(669, 'Pálmazsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(636, 'Pancetta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(647, 'Pangasius');
INSERT INTO `ingredient` (`id`, `name`) VALUES(694, 'Panko');
INSERT INTO `ingredient` (`id`, `name`) VALUES (646, 'Papaja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(638, 'Paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(652, 'Paprikakrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES (670, 'Paprikás kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(657, 'Paprikás szalámi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(626, 'Paradicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(655, 'Paradicsomlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(696, 'Paradicsomos babkonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(693, 'Paradicsomos salsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(675, 'Paradicsompaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(691, 'Paradicsomszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(677, 'Parasztkolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(678, 'Parázskrumpli');
INSERT INTO `ingredient` (`id`, `name`) VALUES (676, 'Parenyica sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(658, 'Párizsi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(659, 'Pármai sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(628, 'Parmezán sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(689, 'Passzírozott paradicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(695, 'Pastrami');
INSERT INTO `ingredient` (`id`, `name`) VALUES(649, 'Patisszon');
INSERT INTO `ingredient` (`id`, `name`) VALUES(679, 'Pattogatott kukorica');
INSERT INTO `ingredient` (`id`, `name`) VALUES(671, 'Pecorino sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(680, 'Pecsenyezsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(674, 'Pekándió');
INSERT INTO `ingredient` (`id`, `name`) VALUES(656, 'Penne');
INSERT INTO `ingredient` (`id`, `name`) VALUES(654, 'Pepperoni');
INSERT INTO `ingredient` (`id`, `name`) VALUES(634, 'Pesto');
INSERT INTO `ingredient` (`id`, `name`) VALUES(627, 'Petrezselyem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(642, 'Pezsgő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(648, 'Pillecukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(672, 'Piros curry paszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(666, 'Piros kaliforniai paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(635, 'Piros ribizli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(660, 'Piskótalap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(681, 'Piskótarolád');
INSERT INTO `ingredient` (`id`, `name`) VALUES(682, 'Piskótatallér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(639, 'Pisztácia');
INSERT INTO `ingredient` (`id`, `name`) VALUES(645, 'Pisztráng');
INSERT INTO `ingredient` (`id`, `name`) VALUES(637, 'Pita');
INSERT INTO `ingredient` (`id`, `name`) VALUES(673, 'Pizza fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(661, 'Pizzaszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(683, 'Pizzatészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(640, 'Polip');
INSERT INTO `ingredient` (`id`, `name`) VALUES(643, 'Pomelo');
INSERT INTO `ingredient` (`id`, `name`) VALUES(632, 'Ponty');
INSERT INTO `ingredient` (`id`, `name`) VALUES(664, 'Porcukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(630, 'Póréhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(653, 'Portobello gomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(684, 'Prágai sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(685, 'Pritaminpaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(629, 'Prosciutto');
INSERT INTO `ingredient` (`id`, `name`) VALUES(692, 'Prosecco - habzóbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(651, 'Pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(650, 'Puffasztott rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(663, 'Pulykacomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES (665, 'Pulykafelsőcomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(687, 'Pulykahere');
INSERT INTO `ingredient` (`id`, `name`) VALUES(633, 'Pulykahús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(641, 'Pulykamáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(662, 'Pulykamell');
INSERT INTO `ingredient` (`id`, `name`) VALUES(667, 'Pulykamellsonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(690, 'Pulykanyak');
INSERT INTO `ingredient` (`id`, `name`) VALUES(686, 'Pulykazúza');
INSERT INTO `ingredient` (`id`, `name`) VALUES(688, 'Puncsaroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(703, 'Radicchio');
INSERT INTO `ingredient` (`id`, `name`) VALUES(741, 'Raffaello golyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(719, 'Rahát');
INSERT INTO `ingredient` (`id`, `name`) VALUES(725, 'Raklett sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(742, 'Rákpaszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(744, 'Rama');
INSERT INTO `ingredient` (`id`, `name`) VALUES(746, 'Rántott sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(740, 'Ras el hanout');
INSERT INTO `ingredient` (`id`, `name`) VALUES(711, 'Rebarbara');
INSERT INTO `ingredient` (`id`, `name`) VALUES(712, 'Repceolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(709, 'Retek');
INSERT INTO `ingredient` (`id`, `name`) VALUES(743, 'Reteklevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(713, 'Réteslap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(721, 'Rétesliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(728, 'Ribizliszörp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(700, 'Ricotta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(726, 'Rigatoni tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(729, 'Ringlószilva');
INSERT INTO `ingredient` (`id`, `name`) VALUES(720, 'Rizottó rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(699, 'Rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(723, 'Rizsborecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(745, 'Rizsdara');
INSERT INTO `ingredient` (`id`, `name`) VALUES(710, 'Rizsecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(738, 'Rizslap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(716, 'Rizsliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(737, 'Rizspehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(727, 'Rizstej');
INSERT INTO `ingredient` (`id`, `name`) VALUES (704, 'Rizstészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(706, 'Rókagomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(718, 'Roletti');
INSERT INTO `ingredient` (`id`, `name`) VALUES(708, 'Római kömény');
INSERT INTO `ingredient` (`id`, `name`) VALUES(715, 'Római saláta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(730, 'Rooibos');
INSERT INTO `ingredient` (`id`, `name`) VALUES(739, 'Ropi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(717, 'Rosé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(735, 'Rostos almalé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(733, 'Rostos gyümölcslé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(698, 'Rozmaring');
INSERT INTO `ingredient` (`id`, `name`) VALUES(731, 'Rozs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(736, 'Rózsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(714, 'Rózsabors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(724, 'Rózsaburgonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(705, 'Rózsavíz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(732, 'Rozskenyér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(707, 'Rozsliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(734, 'Rozspehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(701, 'Rukkola');
INSERT INTO `ingredient` (`id`, `name`) VALUES(702, 'Rum');
INSERT INTO `ingredient` (`id`, `name`) VALUES(722, 'Rumaroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(757, 'Sáfrány');
INSERT INTO `ingredient` (`id`, `name`) VALUES(749, 'Sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(793, 'Sajtos tortellini');
INSERT INTO `ingredient` (`id`, `name`) VALUES(795, 'Sajtszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(791, 'Salátakeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(789, 'Salátalevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(754, 'Salottahagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(797, 'Sangría');
INSERT INTO `ingredient` (`id`, `name`) VALUES(788, 'Sárga currykrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(823, 'Sárga kaliforniai paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(756, 'Sárgabarack');
INSERT INTO `ingredient` (`id`, `name`) VALUES(819, 'Sárgabarackbefőtt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(790, 'Sárgabarackdzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(784, 'Sárgabaracklekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(826, 'Sárgabarackmag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(798, 'Sárgaborsóliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(765, 'Sárgadinnye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(747, 'Sárgarépa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(830, 'Sárkánygyümölcs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(750, 'Savanyú káposzta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(827, 'Savanyúkáposztalé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(792, 'Savó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(804, 'Selyemsonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(753, 'Serrano sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(817, 'Sertés agyvelő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(777, 'Sertés karajcsont');
INSERT INTO `ingredient` (`id`, `name`) VALUES(776, 'Sertés rövidkaraj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(778, 'Sertés szűzpecsenye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(806, 'Sertés virsli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(796, 'Sertésborda');
INSERT INTO `ingredient` (`id`, `name`) VALUES(822, 'Sertésbőrke');
INSERT INTO `ingredient` (`id`, `name`) VALUES(774, 'Sertéscomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(799, 'Sertéscsont');
INSERT INTO `ingredient` (`id`, `name`) VALUES(782, 'Sertéscsülök');
INSERT INTO `ingredient` (`id`, `name`) VALUES(775, 'Sertésdagadó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(801, 'Sertésfarok');
INSERT INTO `ingredient` (`id`, `name`) VALUES(825, 'Sertésfej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(794, 'Sertésfül');
INSERT INTO `ingredient` (`id`, `name`) VALUES(772, 'Sertésháj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(751, 'Sertéshús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(781, 'Sertésköröm');
INSERT INTO `ingredient` (`id`, `name`) VALUES(783, 'Sertéslapocka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(770, 'Sertésmáj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(815, 'Sertésnyelv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(779, 'Sertésoldalas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(802, 'Sertésorr');
INSERT INTO `ingredient` (`id`, `name`) VALUES(814, 'Sertésszív');
INSERT INTO `ingredient` (`id`, `name`) VALUES(780, 'Sertéstarja');
INSERT INTO `ingredient` (`id`, `name`) VALUES(821, 'Sertéstüdő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(818, 'Sertésvelő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(820, 'Sertésvér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(805, 'Sertésvese');
INSERT INTO `ingredient` (`id`, `name`) VALUES(758, 'Sertészsír');
INSERT INTO `ingredient` (`id`, `name`) VALUES(768, 'Sherry');
INSERT INTO `ingredient` (`id`, `name`) VALUES(759, 'Shiitake gomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(824, 'Snickers szelet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(760, 'Snidling');
INSERT INTO `ingredient` (`id`, `name`) VALUES(755, 'Só');
INSERT INTO `ingredient` (`id`, `name`) VALUES(829, 'Soba tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(800, 'Som');
INSERT INTO `ingredient` (`id`, `name`) VALUES (764, 'Sonka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(803, 'Sonkalé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(807, 'Sonkás szalámi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(785, 'Sonkás tortellini');
INSERT INTO `ingredient` (`id`, `name`) VALUES(762, 'Sóska');
INSERT INTO `ingredient` (`id`, `name`) VALUES(786, 'Sovány tej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(787, 'Sovány túró');
INSERT INTO `ingredient` (`id`, `name`) VALUES(828, 'Sózott retek');
INSERT INTO `ingredient` (`id`, `name`) VALUES(766, 'Sör');
INSERT INTO `ingredient` (`id`, `name`) VALUES(816, 'Sötét trombitagomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(773, 'Spagetti tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(808, 'Spatzle tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(752, 'Spenót');
INSERT INTO `ingredient` (`id`, `name`) VALUES(761, 'Stevia');
INSERT INTO `ingredient` (`id`, `name`) VALUES(809, 'Stevia por');
INSERT INTO `ingredient` (`id`, `name`) VALUES(769, 'Surimi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(810, 'Sushi rizs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(811, 'Sügér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(767, 'Süllő/ fogas');
INSERT INTO `ingredient` (`id`, `name`) VALUES(771, 'Sűrített paradicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(812, 'Sütésálló lekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(813, 'Sütnivaló kolbász');
INSERT INTO `ingredient` (`id`, `name`) VALUES(831, 'Sütőmargarin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(763, 'Sütőpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(748, 'Sütőtök');
INSERT INTO `ingredient` (`id`, `name`) VALUES(838, 'Szaké');
INSERT INTO `ingredient` (`id`, `name`) VALUES(850, 'Szalámi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(848, 'Szalicil');
INSERT INTO `ingredient` (`id`, `name`) VALUES(856, 'Szamóca');
INSERT INTO `ingredient` (`id`, `name`) VALUES(857, 'Szamócadzsem');
INSERT INTO `ingredient` (`id`, `name`) VALUES(853, 'Száraz rosé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(852, 'Száraz vörösbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(834, 'Szardella (konzerv)');
INSERT INTO `ingredient` (`id`, `name`) VALUES(858, 'Szardellapaszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(859, 'Szardínia');
INSERT INTO `ingredient` (`id`, `name`) VALUES(881, 'Szárított almakarika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(882, 'Szárított fűszerpaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(873, 'Szárított gomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(878, 'Szárított hibiszkusz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(874, 'Szárított hibiszkuszvirág');
INSERT INTO `ingredient` (`id`, `name`) VALUES(879, 'Szárított jázmin');
INSERT INTO `ingredient` (`id`, `name`) VALUES (835, 'Szárított paradicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(877, 'Szárított rák');
INSERT INTO `ingredient` (`id`, `name`) VALUES(860, 'Szárnyas alaplé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(861, 'Szárnyas fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(862, 'Szarvacska tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(863, 'Szarvasbélszín');
INSERT INTO `ingredient` (`id`, `name`) VALUES(871, 'Szarvascomb');
INSERT INTO `ingredient` (`id`, `name`) VALUES(845, 'Szarvasgomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(846, 'Szarvashús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(883, 'Százszorszép');
INSERT INTO `ingredient` (`id`, `name`) VALUES(832, 'Szeder');
INSERT INTO `ingredient` (`id`, `name`) VALUES(855, 'Szegfűbors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(870, 'Szegfűgomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(833, 'Szegfűszeg');
INSERT INTO `ingredient` (`id`, `name`) VALUES(884, 'Szénsavas citromos üdítőital');
INSERT INTO `ingredient` (`id`, `name`) VALUES(854, 'Szénsavas narancsos üdítőital');
INSERT INTO `ingredient` (`id`, `name`) VALUES(880, 'Szentjánoskenyérmag liszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(836, 'Szerecsendió');
INSERT INTO `ingredient` (`id`, `name`) VALUES(840, 'Szezámmag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(844, 'Szezámolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(839, 'Szilva');
INSERT INTO `ingredient` (`id`, `name`) VALUES(864, 'Szilvabefőtt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(851, 'Szilvalekvár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(865, 'Színes cukorka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(841, 'Szódabikarbóna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(869, 'Szódavíz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(847, 'Szója');
INSERT INTO `ingredient` (`id`, `name`) VALUES(849, 'Szójabab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(875, 'Szójaliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(876, 'Szójaolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(837, 'Szójaszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(842, 'Szőlő');
INSERT INTO `ingredient` (`id`, `name`) VALUES (866, 'Szőlőcukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(867, 'Szőlőlé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(868, 'Szőlőlevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(843, 'Szőlőmagolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(872, 'Szörp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(912, 'Tabasco szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(958, 'Tagliatelle');
INSERT INTO `ingredient` (`id`, `name`) VALUES(954, 'Tamarind paszta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(952, 'Tandoori masala');
INSERT INTO `ingredient` (`id`, `name`) VALUES(971, 'Tangelo');
INSERT INTO `ingredient` (`id`, `name`) VALUES(927, 'Tápióka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(928, 'Tápiókaliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(894, 'Tarhonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(893, 'Tárkony');
INSERT INTO `ingredient` (`id`, `name`) VALUES(929, 'Tárkonyecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(930, 'Tartármártás');
INSERT INTO `ingredient` (`id`, `name`) VALUES (965, 'Tatárbifsztek');
INSERT INTO `ingredient` (`id`, `name`) VALUES(910, 'Tea');
INSERT INTO `ingredient` (`id`, `name`) VALUES(921, 'Teavaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(890, 'Tehéntúró');
INSERT INTO `ingredient` (`id`, `name`) VALUES(888, 'Tej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(914, 'Tejcsokoládé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(889, 'Tejföl');
INSERT INTO `ingredient` (`id`, `name`) VALUES(931, 'Tejkaramella');
INSERT INTO `ingredient` (`id`, `name`) VALUES(969, 'Tejoltó enzim');
INSERT INTO `ingredient` (`id`, `name`) VALUES(907, 'Tejpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(922, 'Tejszínhab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(923, 'Tejszínhab por');
INSERT INTO `ingredient` (`id`, `name`) VALUES(932, 'Téliszalámi');
INSERT INTO `ingredient` (`id`, `name`) VALUES(920, 'Teljes kiőrlésű liszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(933, 'Teljeskiőrlésű tönkölybúza liszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(947, 'Tenger gyümölcsei mix');
INSERT INTO `ingredient` (`id`, `name`) VALUES (970, 'Tengeri hínár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(944, 'Tengeri spárga');
INSERT INTO `ingredient` (`id`, `name`) VALUES(900, 'Tepertő');
INSERT INTO `ingredient` (`id`, `name`) VALUES(905, 'Tequila');
INSERT INTO `ingredient` (`id`, `name`) VALUES(963, 'Teriyaki szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(891, 'Tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(941, 'Thai halszósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(949, 'Thai zöldségkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(957, 'Tigrisrák');
INSERT INTO `ingredient` (`id`, `name`) VALUES(911, 'Tilápia');
INSERT INTO `ingredient` (`id`, `name`) VALUES(955, 'Timsó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(899, 'Tintahal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(962, 'Tintahal tinta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(940, 'Tintahalcsáp');
INSERT INTO `ingredient` (`id`, `name`) VALUES(925, 'Tintahalkarika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(945, 'Tiszta szesz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(939, 'Toast kenyér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(953, 'Toffifee');
INSERT INTO `ingredient` (`id`, `name`) VALUES(892, 'Tofu');
INSERT INTO `ingredient` (`id`, `name`) VALUES(885, 'Tojás');
INSERT INTO `ingredient` (`id`, `name`) VALUES(916, 'Tojásfehérje');
INSERT INTO `ingredient` (`id`, `name`) VALUES(906, 'Tojáslikőr');
INSERT INTO `ingredient` (`id`, `name`) VALUES(950, 'Tojáspótló por');
INSERT INTO `ingredient` (`id`, `name`) VALUES(915, 'Tojássárgája');
INSERT INTO `ingredient` (`id`, `name`) VALUES(956, 'Tokaszalonna');
INSERT INTO `ingredient` (`id`, `name`) VALUES(960, 'Tomatillo (mexikói földicseresznye)');
INSERT INTO `ingredient` (`id`, `name`) VALUES (887, 'Tonhal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(934, 'Tonhalkonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(935, 'Tonik');
INSERT INTO `ingredient` (`id`, `name`) VALUES(959, 'Tonkabab');
INSERT INTO `ingredient` (`id`, `name`) VALUES (903, 'Torma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(909, 'Tortabevonó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(904, 'Tortazselé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(908, 'Tortellini');
INSERT INTO `ingredient` (`id`, `name`) VALUES(966, 'Tortelloni');
INSERT INTO `ingredient` (`id`, `name`) VALUES(926, 'Tortilla chips');
INSERT INTO `ingredient` (`id`, `name`) VALUES(919, 'Tortilla lap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(961, 'Tostada lap');
INSERT INTO `ingredient` (`id`, `name`) VALUES(936, 'Tőkehalfilé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(896, 'Tökmag');
INSERT INTO `ingredient` (`id`, `name`) VALUES(964, 'Tökmagkrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES (942, 'Tökmagliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(897, 'Tökmagolaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(913, 'Tölcsér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(924, 'Tömlős krémsajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(898, 'Tönkölybúza');
INSERT INTO `ingredient` (`id`, `name`) VALUES (937, 'Tönkölybúza liszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES (951, 'Tönkölybúzapehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES (943, 'Törökméz');
INSERT INTO `ingredient` (`id`, `name`) VALUES (902, 'Törökmogyoró');
INSERT INTO `ingredient` (`id`, `name`) VALUES (901, 'Törpeharcsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(886, 'Tőzegáfonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(918, 'Trappista sajt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(938, 'Triple sec');
INSERT INTO `ingredient` (`id`, `name`) VALUES(946, 'Trópusi gyümölcskonzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES (968, 'Trüffelgolyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES (895, 'Turbolya');
INSERT INTO `ingredient` (`id`, `name`) VALUES (948, 'Túró Rudi');
INSERT INTO `ingredient` (`id`, `name`) VALUES (967, 'Tükörglazúrpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES (917, 'TV paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES (972, 'Tyúk');
INSERT INTO `ingredient` (`id`, `name`) VALUES (973, 'Tyúkháj');
INSERT INTO `ingredient` (`id`, `name`) VALUES (974, 'Uborka');
INSERT INTO `ingredient` (`id`, `name`) VALUES (975, 'Udon tészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES (977, 'Újhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES (979, 'Újhagyma zöldje');
INSERT INTO `ingredient` (`id`, `name`) VALUES (978, 'Újkrumpli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(976, 'Unicum');
INSERT INTO `ingredient` (`id`, `name`) VALUES(980, 'Útifű maghéj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(981, 'Üvegtészta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1019, 'Vad fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(993, 'Vaddisznóhús');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1011, 'Vaddisznókaraj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1010, 'Vaddisznószűz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1008, 'Vadkacsamell');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1004, 'Vadlazac');
INSERT INTO `ingredient` (`id`, `name`) VALUES(985, 'Vaj');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1024, 'Vajbab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1021, 'Vajhal');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1015, 'Vajkaramella');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1002, 'Vajkrém');
INSERT INTO `ingredient` (`id`, `name`) VALUES(987, 'Vajrépa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(986, 'Vanília');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1016, 'Vanília fagylalt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1014, 'Vanília kivonat');
INSERT INTO `ingredient` (`id`, `name`) VALUES(994, 'Vaníliaaroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1009, 'Vaníliapuding');
INSERT INTO `ingredient` (`id`, `name`) VALUES(989, 'Vaníliás cukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(996, 'Vaníliás pudingpor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1022, 'Vanillincukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(982, 'Vargánya gomba');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1012, 'Vargánya gombapor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1017, 'Vegyes savanyúság');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1025, 'Vékonybél (sertés)');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1013, 'Véres hurka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1005, 'Vérnarancs');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1006, 'Vérnarancs aroma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1001, 'Vinaigrette');
INSERT INTO `ingredient` (`id`, `name`) VALUES(997, 'Virágméz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(991, 'Virsli');
INSERT INTO `ingredient` (`id`, `name`) VALUES(990, 'Vitéz szemling');
INSERT INTO `ingredient` (`id`, `name`) VALUES(988, 'Víz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1020, 'Vízigesztenye');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1023, 'Vízispenót');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1018, 'Vízitorma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(998, 'Vodka');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1007, 'Vörösáfonya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1000, 'Vörösbab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(992, 'Vörösbor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(995, 'Vörösborecet');
INSERT INTO `ingredient` (`id`, `name`) VALUES(984, 'Vöröshagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(983, 'Vöröskáposzta');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1003, 'Vöröskaviár');
INSERT INTO `ingredient` (`id`, `name`) VALUES(999, 'Vöröslencse');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1026, 'Wakame');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1030, 'Wasabi konzerv');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1028, 'Whiskey');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1029, 'Wok fűszerkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1027, 'Worcestershire-szósz');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1031, 'Xilit');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1035, 'Zab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1047, 'Zabkorpa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1046, 'Zabliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1039, 'Zabpehely');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1049, 'Zabpehelyliszt');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1041, 'Zabtej');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1034, 'Zeller');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1038, 'Zellerlevél');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1054, 'Zellersó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1055, 'Zöld kaliforniai paprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1050, 'Zöld kardamom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1045, 'Zöld mandula');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1048, 'Zöld olajbogyó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1033, 'Zöldbab');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1058, 'Zöldbab-vajbab keverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1040, 'Zöldbors');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1032, 'Zöldborsó');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1057, 'Zöldborsó-kukorica zöldségkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1053, 'Zöldfűszer');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1043, 'Zöldhagyma');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1036, 'Zöldkagyló');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1042, 'Zöldpaprika');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1044, 'Zöldparadicsom');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1051, 'Zöldség alaplé');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1056, 'Zöldségkeverék');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1052, 'Zöldspárga');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1059, 'Zsálya');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1060, 'Zselatin');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1063, 'Zselatinfix');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1065, 'Zselécukor');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1066, 'Zselésítő befőzőszer');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1062, 'Zsemle');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1061, 'Zsemlemorzsa');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1064, 'Zsúrkenyér');
INSERT INTO `ingredient` (`id`, `name`) VALUES(1037, 'Zúza');

INSERT INTO `recipe_category` (`id`, `name`) VALUES(3, 'aprósütemény');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(1, 'befőttek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(39, 'bonbonok');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(2, 'édes keksz');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(4, 'édes krém');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(5, 'édes süti');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(11, 'egytálételek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(18, 'fagyi');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(19, 'fánk');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(21, 'felfújtak');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(22, 'főzelékek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(25, 'halételek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(26, 'húsételek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(27, 'italok');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(7, 'kelt tészta');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(8, 'kenyerek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(12, 'köretek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(13, 'kuglóf');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(15, 'lángos');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(16, 'lekvárok-dzsemek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(17, 'levesek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(28, 'muffin');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(29, 'palacsinta');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(30, 'péksütemény');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(31, 'pite');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(32, 'pizza');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(33, 'pogácsa');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(34, 'pörkölt');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(35, 'rétes');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(36, 'saláta');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(37, 'savanyúság');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(38, 'sós krémek');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(24, 'sós süti');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(23, 'szendvics');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(20, 'szósz');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(14, 'tapas');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(10, 'tészta');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(6, 'torta');
INSERT INTO `recipe_category` (`id`, `name`) VALUES(9, 'töltött zöldség');
